package mes.inc.aic.common.constants

const val NETWORK_IMAGE = "NETWORK_IMAGE"
const val NETWORK_IMAGE_LOADER = "NETWORK_IMAGE_LOADER"
const val HOMES_SCREEN_REEL = "HOMES_SCREEN_REEL"
const val HOMES_SCREEN_ARTWORKS = "HOMES_SCREEN_ARTWORKS"
const val HOMES_SCREEN_REFRESH_BUTTON = "HOMES_SCREEN_REFRESH_BUTTON"